### ISSUE TITLE
Head: support - input

### ISSUE THREAD

**Issue by GrayJack** [GrayJack/coreutils#117]
**Is your feature request related to a problem? Please describe.**
Nope

**Describe the solution you'd like**
Support for `-` as input on head tool

**Describe alternatives you've considered**
Not support at all. Most BSD (I think Solaris and MacOS as well) don't have it and are fine with it.
But since other tools in this repository support this kind of input for files,  why not support for head as well

**Additional context**
None

**Comment by GrayJack** [comment]
@twe4ked Can I mark you for code review when I or someone else implements it? Asking because you implemented it

**Comment by twe4ked** [comment]
You sure can :)
