### ISSUE TITLE
Uniq: Implement -f option

### ISSUE THREAD

**Issue by marcospb19** [GrayJack/coreutils#122]
### Description:
Implement `-f`/`--skip-fields` to Uniq.

From [the standard](https://pubs.opengroup.org/onlinepubs/9699919799/utilities/uniq.html):

> -f  fields
Ignore the first fields fields on each input line when doing comparisons, where fields is a positive decimal integer. A field is the maximal string matched by the basic regular expression:
`[[:blank:]]*[^[:blank:]]*`
> 
> If the fields option-argument specifies more fields than appear on an input line, a null string shall be used for comparison.

---

Obs: I did not implemented in #121 because I could not understand while testing with GNU Coreutils' Uniq how this works.

When I called:
```sh
uniq -c -f 1 << EOF       
a b
c b
EOF
```

I expected:
```sh
      2 b
```

But instead, I got:
```sh
      2 a b
```

**Comment by marcospb19** [comment]
Hey, @GrayJack, assign me for this! :smile: 

I'm focusing in one of my personal projects, but I'm planing to implement it in october, is it alright?

**Comment by marcospb19** [comment]
I understood how it works heheh.

![image](https://user-images.githubusercontent.com/38900226/92308005-c7760e80-ef70-11ea-8c03-a2a9f83e15fc.png)

It ignores the comparison of the first fields, but displays the text of the first one.

**Comment by GrayJack** [comment]
Yes, I can!! Np

**Comment by marcospb19** [comment]
Hahahah you just guessed that I want the `hacktoberfest` t-shirt  :eyes:.

**Comment by GrayJack** [comment]
LOL, no, I have to put this label on other issues as well, last year hacktoberfest brought a lot of contributions!! It was super nice and fun

**Comment by marcospb19** [comment]
Done :D #131
