### ISSUE TITLE
Implement chroot

### ISSUE THREAD

**Issue by GrayJack** [GrayJack/coreutils#14]

**Comment by ladysamantha** [comment]
I'm happy to take this one!

Quick question: should it be implementing the [Linux options flavor](https://linux.die.net/man/1/chroot) or the [BSD flavor](https://www.freebsd.org/cgi/man.cgi?chroot(8))? Or should it be like the uutils version [which seems to have a mix of both](https://github.com/uutils/coreutils/blob/master/src/chroot/chroot.rs#L35)?

**Comment by GrayJack** [comment]
Since I require to have both long and short for flags/options, it would be a mix of both.

Remember to look at the [contribution guide](https://github.com/GrayJack/coreutils/blob/master/CONTRIBUTING.md) and have fun :smile:
