### ISSUE TITLE
Implement csplit

### ISSUE THREAD

**Issue by GrayJack** [GrayJack/coreutils#17]

**Comment by mkindahl** [comment]
I could take a shot at this one.

**Comment by GrayJack** [comment]
Sure, have fun :smile:

**Comment by mkindahl** [comment]
Most of the implementation is done in https://github.com/GrayJack/coreutils/pull/109. What remains are:

- #111
- #112 
- #113

**Comment by mkindahl** [comment]
I think this issue can be closed and the remaining work are in the issues quoted above.
