### ISSUE TITLE
Implement cut

### ISSUE THREAD

**Issue by GrayJack** [GrayJack/coreutils#18]

**Comment by mkindahl** [comment]
I could take a cut at this utility. :)

Which one should be implemented?
- Linux version: http://man7.org/linux/man-pages/man1/cut.1.html
- POSIX version: https://pubs.opengroup.org/onlinepubs/9699919799/utilities/cut.html

Linux version ignores some POSIX options (actually only `-n` it seems).

**Comment by GrayJack** [comment]
If you feel like it, implement all the features of POSIX + extra Linux features.

Also, don't forget to use git message style on CONTRIBUTING.md on your commit messages
