### ISSUE TITLE
Implement rm

### ISSUE THREAD

**Issue by GrayJack** [GrayJack/coreutils#42]

**Comment by Larisho** [comment]
I'd like to take this one!

**Comment by GrayJack** [comment]
Have fun :smile:

**Comment by Larisho** [comment]
Quick question: in the `rm` utility, there's a `-i` flag, a `-I` flag, and then the long version is `--interactive=(never|once|always)`. Should I stick to the "always a short and long option" rule or make it compatible with the GNU version of `rm`?

**Comment by GrayJack** [comment]
I would like that  "always a short and long option" rule continue, if you want to implement a specific options of other coreutils and there is only one of them, create the other one

Like I did with `id`, BSDs coreutils all have a `-p` flag, but no long version, so I just named the long `--pretty`

**Comment by Larisho** [comment]
Thanks!
