### ISSUE TITLE
Implement touch

### ISSUE THREAD

**Issue by GrayJack** [GrayJack/coreutils#54]

**Comment by MichelKansou** [comment]
I'm interested in taking a look at this for Hacktoberfest and also will help my skills in Rust 😁

**Comment by GrayJack** [comment]
Nice, have fun!! :smile:

**Comment by Ashwin-A-K** [comment]
Is it ok... if i work on this ?

**Comment by MichelKansou** [comment]
@Ashwin-A-K I already finished touch initial implementation I still need to finish the unit test for it

**Comment by Ashwin-A-K** [comment]
Ok,,. Cool👍🏻
