### ISSUE TITLE
Implement uptime

### ISSUE THREAD

**Issue by GrayJack** [GrayJack/coreutils#59]

**Comment by Celeo** [comment]
For this command, what do you want it to return? I.e. gnu uptime returns a line of current time, system uptime (configurable with --pretty or --since), user count, and average load.

**Comment by GrayJack** [comment]
For that, Since it's just 3 different behaviors and all make a lot of sense to me, all of gnu flags are wanted

**Comment by GrayJack** [comment]
@Celeo Are you already working on this? I self-assigned me cause I forgot that you were interested

**Comment by Celeo** [comment]
I was playing around with it, but I can't commit right now to doing it in a timely manner.

**Comment by GrayJack** [comment]
Would be ok if I did it?

**Comment by Celeo** [comment]
Absolutely. Feel free to pull anything from what I did get done if it helps! https://github.com/Celeo/coreutils/commit/1aed0d138286e9cbfa7d67597dbcef842d8c074a

**Comment by GrayJack** [comment]
Done, only blocking stuff is the lack o utmpx on OpenBSD and the libc crate not exposing utmpx.h API on NetBSD and Solaris
