### ISSUE TITLE
[BUG] Actions: Build for OpenBSD, DragonflyBSD, and Haiku broken

### ISSUE THREAD

**Issue by Larisho** [GrayJack/coreutils#73]
Currently, the actions for those databases are trying to download the wrong toolchains.
According to https://forge.rust-lang.org/release/platform-support.html,

OpenBSD: x86_64-unknown-openbsd
DragonflyBSD: x86_64-unknown-dragonfly
Haiku: x86_64-unknown-haiku

**Comment by Larisho** [comment]
Sorry--you're right. I misread the error in the logs. Closing

**Comment by GrayJack** [comment]
No worries, that problem that made me insert a manual compilation in the table
