### ISSUE TITLE
Implement shutdown

### ISSUE THREAD

**Issue by Ashwin-A-K** [GrayJack/coreutils#78]

**Comment by GrayJack** [comment]
Shutdown is not part of any coreutils that I'm aware of :thinking: 

What are your thought on this?

**Comment by Ashwin-A-K** [comment]
I wasn't sure about that. I wanted to ask.

**Comment by GrayJack** [comment]
I've been searching, normally is the init system that implement that

**Comment by Ashwin-A-K** [comment]
Ok..
