### ISSUE TITLE
Implement expand

### ISSUE THREAD

**Issue by GrayJack** [GrayJack/coreutils#8]

**Comment by muskuloes** [comment]
Hi @GrayJack , Can I work on this?

**Comment by GrayJack** [comment]
Yes, of course :smile:

**Comment by muskuloes** [comment]
Hi, sorry for the inactivity on this issue. I haven't had the time to work on it yet. Also, I've seen that `unexpand` has already been implemented. So, if @bojan88 (whom I know from another project) wouldn't mind, he can implement this one as well :) .

**Comment by bojan88** [comment]
Please, feel free to implement it. Of course I don't mind.
I might join for code reviews

**Comment by muskuloes** [comment]
It's best that you do `expand` as it'll be very similar to `unexpand` and you already own the code for that. I won't like to have my name on it, if I just mostly copied your code. I'll find some other issue to work on some other time 😉.

**Comment by GrayJack** [comment]
In that case, if most of the code is copied, is just a matter to put his name (with yours too) on the crate and author text

**Comment by bojan88** [comment]
I also don't mind if you copy most of my code.

**Comment by muskuloes** [comment]
Alright guys. I'll do it in the week. @bojan88, I'll add your name as author and will appreciate you reviewing the PR 😅.
