### ISSUE TITLE
[BUG] Rmdir: error when -Ip on legit cases

### ISSUE THREAD

**Issue by GrayJack** [GrayJack/coreutils#80]
**Describe the bug**
When using both `-p` and `-I` on rmdir, it will give a error when not needed

Looking at the implementation, when both FLAGS happens at the same time, `fs::remove_dir()` will be called twice for the same target

**To Reproduce**
1. Run command with `-pI <dir>`
2. See error

**Expected behavior**
Exit with no errors

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Linux 5.3.2
 - Rust Version: 1.38
 - Software Version: 0.0.0

**Comment by GrayJack** [comment]
@silverweed It's fine for you that I change come of your code? I just noticed this bug because of a few tests that I didn't thought back then and had to use today

**Comment by silverweed** [comment]
Sure, please do!
